---
ID: "bfd75586-4f09-4cf9-a611-a10b9b27409b"
Parent: "4548b988-2148-4888-8846-ee38b7ca8f16"
Template: "4548b988-2148-4888-8846-ee38b7ca8f16"
Path: /sitecore/templates/Feature/Content/Apply Online Tab Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180301T090323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
