---
ID: "cfe6e0b6-d17f-4e34-9749-bd5ff9233be7"
Parent: "950ddb63-2b49-46f1-b7ed-d0f2f98c8a11"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Feature/Content/Article/Product Detail
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180315T041056Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
