---
ID: "1c67b79e-88c0-4486-8b69-66cf2eb60557"
Parent: "0d74fce9-ce0f-43f3-a98a-f00c935b13cc"
Template: "0d74fce9-ce0f-43f3-a98a-f00c935b13cc"
Path: /sitecore/templates/Feature/Content/Banner with Icon/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{42F50E61-72E9-49A7-8BEE-74BB206B2DF0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180916T095700Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
