---
ID: "2dd5dc24-4f03-4f6b-af5a-3f2b0196e9ab"
Parent: "915eb6cb-6403-40ed-bd8d-45dcffed4e2d"
Template: "99f8905d-4a87-4eb8-9f8b-a9bebfb3add6"
Path: /sitecore/layout/Renderings/Feature/Content/Product Detail Syariah
DB: master
SharedFields:
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/Content/Product Detail Syariah Content
- ID: "51b435bc-f7b9-478a-9c51-52916af96ff5"
  Hint: Path
  Value: /Views/Content/ProductDetailSyariah.cshtml
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "{4FB25B9C-843D-4368-A26E-5A0CC06352AF}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediapath="" alt="product-detail-syariah" width="" height="" hspace="" vspace="" showineditor="" usethumbnail="" src="" mediaid="{6B5590FE-8759-42A1-9163-6478588BE6E0}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T081619Z
