---
ID: "89b91d1b-57be-4cc8-9a4a-4631c145feda"
Parent: "db2763b7-b7f6-43e0-82aa-0edd955effd9"
Template: "db2763b7-b7f6-43e0-82aa-0edd955effd9"
Path: /sitecore/templates/Feature/Content/Image and Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180702T044857Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
