---
ID: "1b5435fb-4327-4ef0-bcbb-ad02a29f9e1d"
Parent: "42f50e61-72e9-49a7-8bee-74bb206b2df0"
Template: "42f50e61-72e9-49a7-8bee-74bb206b2df0"
Path: /sitecore/templates/Feature/Content/Icon with Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180916T101605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
