---
ID: "0bfe67e0-65ee-4983-829a-d05b610e3e53"
Parent: "57350029-1763-4c20-839c-ae65356e3b2f"
Template: "57350029-1763-4c20-839c-ae65356e3b2f"
Path: /sitecore/templates/Feature/Content/Contact Us Tab Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180301T090323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
