---
ID: "421f0c9e-999a-41d4-9a07-234438485e21"
Parent: "e1b114da-7fd2-4af4-98a8-3958e62787de"
Template: "e1b114da-7fd2-4af4-98a8-3958e62787de"
Path: /sitecore/templates/Feature/Content/More Syariah Tab Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180301T090323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
