---
ID: "a66fc57a-c291-4a0b-b227-93a0b50d0242"
Parent: "755e1636-e364-43e3-a929-900c83f303bf"
Template: "755e1636-e364-43e3-a929-900c83f303bf"
Path: /sitecore/templates/Feature/Content/Side Tabs Group/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{EDCAE9D6-29CF-4C25-892B-3F34EA4E1DF7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180723T080346Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
