---
ID: "723e3e05-179e-4eef-a9e3-34b8019556ef"
Parent: "1a2d090d-210f-46ee-9c8a-2f8a0066a802"
Template: "1a2d090d-210f-46ee-9c8a-2f8a0066a802"
Path: /sitecore/templates/Feature/Content/Kurs List Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180301T090323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
