---
ID: "59e73de6-b807-49f1-899a-6342c273b477"
Parent: "bcdf2677-cbb5-4427-b262-329f0295202a"
Template: "bcdf2677-cbb5-4427-b262-329f0295202a"
Path: /sitecore/templates/Feature/Content/Article Tagging Category Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180301T090323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
